### ISSUE TITLE
[Vapor] Core dump

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2575]
Hi,

With the following command 
```
wrk --latency --duration 15s --connections 8 --timeout 8 --threads 8 http://172.17.0.2:3000/
```

I have `double free or corruption (out)` on https://github.com/the-benchmarker/web-frameworks/blob/0fbe4912abc6923ddd625ccbb46349e4d64432ff/swift/vapor-framework/main.swift#L1

Do you need more info to debug ?

**Comment by 0xTim** [comment]
I can reproduce this, I'll investigate it and find a fix

**Comment by 0xTim** [comment]
This should be fixed in #2577

Note that it has required a fair few changes to make it work (and all the other projects!)

**Comment by waghanza** [comment]
Thanks for your work on the other frameworks, however, this one is still failing

**Comment by waghanza** [comment]
@0xTim I have `free(): invalid size`.  The container defintion is
~~~dockerfile
FROM swift:5.2

RUN apt -y update
RUN apt -y install libssl-dev zlib1g-dev libcurl4-openssl-dev uuid-dev

WORKDIR /usr/src/app

COPY Package.swift main.swift ./

RUN swift build -c release

FROM swift:52-slim
COPY --from=0 /usr/src/app/.build/release/server /usr/src/app/.build/release/server
CMD /usr/src/app/.build/release/server serve --env prod
~~~
and the command is `wrk http://172.17.0.2:3000/` where **172.17.0.2** is the container IP

**Comment by waghanza** [comment]
Nevermind, I think I mess up results
